---
title: The Graphics Office
timezone: UTC
collections:
  posts:
    title: Blog
    output: true
  case-study:
    title: Case Studies
    output: true
  research:
    title: Research
    output: true
  shop:
    title: Shop
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: page
- scope:
    path: ''
    type: casestudies
  values:
    layout: page
- scope:
    path: ''
    type: shop
  values:
    layout: page
email: desk@thegraphicsoffice.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
permalink: pretty
exclude:
- node_modules
- gulpfile.js
