---
title: The Graphics Office
timezone: UTC
collections:
  casestudies:
    title: Case Studies
    output: true
  posts:
    title: Posts
    output: true
  shop:
    title: Shop
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: page
- scope:
    path: ''
    type: casestudies
  values:
    layout: page
- scope:
    path: ''
    type: shop
  values:
    layout: page
email: desk@thegraphicsoffice.com
description: TKTKTK
baseurl: ''
url: ''
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-default-layout
permalink: pretty
exclude:
- node_modules
- gulpfile.js
