---
title: The Graphics Office
timezone: America/New_York
collections:
  posts:
    title: Blog
    output: true
  case-study:
    title: Case Studies
    output: true
  research:
    title: Research
    output: true
  shop:
    title: Shop
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: page
- scope:
    path: ''
    type: case-study
  values:
    layout: case-study
- scope:
    path: ''
    type: shop
  values:
    layout: page-shop
- scope:
    path: ''
    type: research
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: page
footer-image: "/uploads/contact-background11.jpg"
email: hello@thegraphicsoffice.com
description: The Graphics Office designs for exhibitions and print. We give visual
  and verbal form to an idea, a notion, a sensibility, a group of facts. Design is
  an important part of every project we do—but it’s not the only part. We believe
  that a larger understanding of subject, history, context, and audience should drive
  graphic solutions. A fascination with type—not only trends, but the history of metal
  and wood type—informs our work. We bring to any work we do a sense of how it sounds
  and reads, and where it fits in the cultural landscape. TGO would like to help you
  meet your goals in the smartest, most attractive way possible. Please get in touch.
baseurl: 
url: 
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-default-layout
- jekyll-redirect-from
permalink: pretty
exclude:
- node_modules
- gulpfile.js
