---
title: The Graphics Office
timezone: America/New_York
collections:
  posts:
    title: Blog
    output: true
    permalink: /research/:title/
  case-study:
    title: Case Studies
    output: true
  research:
    title: Research
    output: true
  shop:
    title: Shop
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: page
- scope:
    path: ''
    type: case-study
  values:
    layout: case-study
- scope:
    path: ''
    type: shop
  values:
    layout: page-shop
- scope:
    path: ''
    type: research
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: page
email: desk@thegraphicsoffice.com
description: TKTKTK
baseurl:
url:
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-default-layout
- jekyll-redirect-from
permalink: pretty
exclude:
- node_modules
- gulpfile.js
