---

title: A Sturdy Son
date: '2014-02-22T19:49:00.000-08:00'
author: Doug Clouse
tags:
- history
- family
modified_time: '2014-03-20T21:01:57.157-07:00'
thumbnail: http://2.bp.blogspot.com/-vQzEKg24K1g/UwluTsHh8PI/AAAAAAAABsE/hcf1obt4-8o/s72-c/vanravenswaay.jpg
blogger_id: tag:blogger.com,1999:blog-2136690105351118519.post-2555299472790548992
blogger_orig_url: http://www.sandislandblog.com/2014/02/a-sturdy-son.html
---

In an earlier <a href="{{ site.baseurl }}{% post_url 2013-08-17-memories-of-kansas %}" target="_blank">post</a> about the book <i>Time's Shadow,</i> I noted the similarities between the author's family and my father's family in Kansas. It seems that the closer American generations were to their European homelands, the more cultured and lively they were. Why? What happened to their children?<br />&nbsp;&nbsp;&nbsp;&nbsp; While doing research about gravestone lettering in Wichita, I came across the book <i>The Arts and Architecture of German Settlements in Missouri: A Survey of a Vanishing Culture</i>, by Charles van Ravenswaay. It is a thorough and informative book and van Ravenswaay's warm, clear writing reveals his close personal connections to the areas of Missouri settled by Germans.<br /><br /><table align="center" cellpadding="0" cellspacing="0" class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;"><tbody><tr><td style="text-align: center;"><a href="http://2.bp.blogspot.com/-vQzEKg24K1g/UwluTsHh8PI/AAAAAAAABsE/hcf1obt4-8o/s1600/vanravenswaay.jpg" imageanchor="1" style="margin-left: auto; margin-right: auto;"><img border="0" src="http://2.bp.blogspot.com/-vQzEKg24K1g/UwluTsHh8PI/AAAAAAAABsE/hcf1obt4-8o/s1600/vanravenswaay.jpg" height="200" width="158" /></a></td></tr><tr><td class="tr-caption" style="text-align: center;">Charles van Ravenswaay</td></tr></tbody></table>In a paragraph that suggests why the children of immigrants became harder and less cultured, Ravenswaay writes about German emigration societies that drew educated Germans to parts of Missouri. These Germans hoped to maintain German intellectual life in America. However, "Missouri was too heavily settled when the immigrants began arriving. Even more important, most of the theorists were incapable of becoming pioneer farmers. Those who came into the area and managed to survive generally did so by raising a crop of sturdy sons, as Richard O'Connor points out in <i>The German-Americans,</i> 'and seeing that they kept their noses out of books.' Otherwise the young men drifted away to the cities to become doctors, lawyers, bankers, and professors. <b>The second generation who remained on the farms replaced the German obsession with <i>Kultur</i> 'with a fixation on hard work and success. The learned German father was a figure of respect, but not of emulation.'"</b><br /><br />My father was one of the "crop of sturdy sons," kept from education by his father. Thankfully, as a younger son he had little to stay in Kansas for, and left to build a life away from the family farm. <span id="goog_1175319472"></span><span id="goog_1175319473"></span>