backend:
  name: github
  repo: caseyg/thegraphicsoffice # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "_uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: "research" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Research" # Used in the UI, ie.: "New Post"
    folder: "_research" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  - name: "work" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Work" # Used in the UI, ie.: "New Post"
    folder: "_work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Thumb", name: "thumb", widget: "image", tagname: "img"}
      - label: "Client"
        name: "client"
        widget: "string"
        required: false
      - label: "Roles"
        name: "roles"
        widget: "list"
        required: false
      - label: "Featured?"
        name: "featured"
        widget: "boolean"
      - label: "Text"
        name: "body"
        widget: "markdown"
      - label: "Sections"
        name: "sections"
        required: false
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Caption", name: "image_caption", widget: "string"}
          - {label: "Text", name: "text", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "select", options: ["left", "center", "full"]}
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie.: "New Post"
    folder: "." # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Portrait", name: "portrait", widget: "image"}
              - {label: "Bio", name: "bio", widget: "text"}
          - {label: "Accolades", name: "accolades", widget: "markdown"}
          - label: "Clients"
            name: "clients"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
